spring:
  application:
    name: blog-api

  datasource:
    url: jdbc:h2:file:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # ✅ 테이블 자동 생성/업데이트
    show-sql: true # ✅ 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # ✅ SQL 로그 포맷 예쁘게 출력
    defer-datasource-initialization: true # ✅ 초기화 시점 늦춤 (데이터 삽입이 가능해짐)

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: user
      password: 1234

server:
  port: 8082
